# Ejercicios Python Pandas

## 1. Creación de un DataFrame con los datos anteriores de todos esos módulos

In [100]:
import numpy as np
import pandas as pd

# tipo dict, se pasa a serie
notas_modulo1= {'Marvin Minsky': 5.7, 'John McCarthy': 6.2, 'Claude Shannon': 6.5, 'Alan Turing': 7.0}
# notas_modulo1_serie= pd.Series(notas_modulo1)
# notas_modulo1_lista = list(notas_modulo1.values())

# tipo list, el problema es que es una lista de tuplas
notas_modulo2= [('Marvin Minsky', 8.0), ('John McCarthy', 8.5), ('Claude Shannon', 8.0), ('Alan Turing', 9.0)]
# Pasar a lista y coger sólo el segundo valor que ya están ordenados
notas_modulo2_lista = []
for tupla in notas_modulo2:
    notas_modulo2_lista.append(tupla[1])      

#tipo set, de tuplas type(notas_modulo3)
notas_modulo3= {('Marvin Minsky', 9.5), ('John McCarthy', 8.9), ('Claude Shannon', 8.7), ('Alan Turing', 9.1)}
#notas_modulo3 = dict(notas_modulo3)

# tipo list, se da por supuesto que está ordenado a los otros módulos
notas_modulo4= [3.3, 4.5, 6.7, 8.9]

# tipo numpy.ndarray, se da por supuesto que está ordenado a los otros módulos
notas_modulo5= np.array([3.5, 4.1, 2.1, 9.3])

# tipo pandas.core.series.Series
notas_modulo6= pd.Series([8.3, 6.5, 5.7, 5.9])
# notas_modulo6_lista = notas_modulo6.tolist()

# tipo pandas.core.series.Series
notas_modulo7= pd.Series([3.3, 4.5, 6.7, 9.9], index=['Marvin Minsky', 'John McCarthy', 'Claude Shannon', 'Alan Turing'])

# tipo pandas.core.series.Series
notas_modulo8= pd.Series({'Marvin Minsky': 5.7, 'John McCarthy': 6.2, 'Claude Shannon': 6.5, 'Alan Turing': 7.0})

#NO se pueden mezclar tipos (salvo las listas, nparray, tuplas con elementos simples), y los indices de los tipos deben ser iguales
notas_df = pd.DataFrame({'Módulo 1': pd.Series(notas_modulo1), 'Módulo 2': notas_modulo2_lista, 'Módulo 3': pd.Series(dict(notas_modulo3)), 'Módulo 4': notas_modulo4, 'Módulo 5': notas_modulo5, 'Módulo 6': notas_modulo6.tolist() , 'Módulo 7': notas_modulo7, 'Módulo 8': notas_modulo8})
#, 'Módulo 2': notas_modulo2, 'Módulo 3': notas_modulo3

# Jupyter en VSCode utiliza un entorno interactivo llamado REPL (Read-Eval-Print Loop). 
# En este entorno, cuando escribes una variable por sí sola y presionas Enter, el intérprete de Python automáticamente llama a la función print() para mostrar el valor de esa variable.
notas_df

# Creación de un DataFrame con los datos anteriores de todos esos módulos
# TODO: Crear el DataFrame

,Módulo 1,Módulo 2,Módulo 3,Módulo 4,Módulo 5,Módulo 6,Módulo 7,Módulo 8
Alan Turing,7.0,8.0,9.1,3.3,3.5,8.3,9.9,7.0
Claude Shannon,6.5,8.5,8.7,4.5,4.1,6.5,6.7,6.5
John McCarthy,6.2,8.0,8.9,6.7,2.1,5.7,4.5,6.2
Marvin Minsky,5.7,9.0,9.5,8.9,9.3,5.9,3.3,5.7